---
services:
  django:
    image: fineants
    build:
      context: .
      dockerfile: "./Dockerfile"
    ports:
      - "8000:8000"
    stdin_open: true
    tty: true
    expose:
      - "8000"
    environment:
      DB_HOST: postgres
      DB_USER: fineants
      DB_PASSWORD: fineants
      DB_NAME: fineants
    depends_on:
      - postgres
    volumes:
      - ./fineants:/home/fineants/app/fineants/
    command: |
      cd /home/fineants/app
      . .venv/bin/activate
      cd fineants-server
      python manage.py migrate
      python manage.py runserver 0.0.0.0:8000
    # command: /usr/bin/zsh -i

  postgres:
    image: postgres:alpine
    ports:
      - "5432:5432"
    expose:
      - "5432"
    restart: always
    environment:
      POSTGRES_PASSWORD: fineants
      POSTGRES_USER: fineants
    volumes:
      - fineants-postgres:/var/lib/postgresql/data

volumes:
  fineants-postgres:
    external: true
