# Generated by Django 3.2.4 on 2021-06-18 19:19

from django.db import migrations
import djmoney.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('wellsfargo', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wellsfargostatement',
            name='beginning_bal',
            field=djmoney.models.fields.MoneyField(decimal_places=4, default_currency='USD', max_digits=19, verbose_name='Beginning Balance'),
        ),
        migrations.AlterField(
            model_name='wellsfargostatement',
            name='ending_bal',
            field=djmoney.models.fields.MoneyField(decimal_places=4, default_currency='USD', max_digits=19, verbose_name='Ending Balance'),
        ),
        migrations.AlterField(
            model_name='wellsfargostatement',
            name='total_credits',
            field=djmoney.models.fields.MoneyField(decimal_places=4, default_currency='USD', max_digits=19, verbose_name='Deposits'),
        ),
        migrations.AlterField(
            model_name='wellsfargostatement',
            name='total_debits',
            field=djmoney.models.fields.MoneyField(decimal_places=4, default_currency='USD', max_digits=19, verbose_name='Withdrawals'),
        ),
    ]
